#!/bin/sh

alias ls='exa --group-directories-first'
alias ll='ls -lah'
alias grep='grep --color=auto'

alias gh='gear -v --hasher -- hsh -v'
alias gch='gear -v --commit --hasher -- hsh -v'
alias ghr='gear -v --hasher -- hsh-rebuild -v'
alias gchr='gear -v --commit --hasher -- hsh-rebuild -v'
alias ghl='gh 2>&1 | tee log.$(seq -f "%02g" $(($(ls log.* | wc -l) + 1)) $(($(ls log.* | wc -l) + 1))).$(date +"%Y-%m-%d-%H-%M-%S-%N")'
alias gchl='gch 2>&1 | tee log.$(seq -f "%02g" $(($(ls log.* | wc -l) + 1)) $(($(ls log.* | wc -l) + 1))).$(date +"%Y-%m-%d-%H-%M-%S-%N")'
alias ghrl='ghr 2>&1 | tee log.$(seq -f "%02g" $(($(ls log.* | wc -l) + 1)) $(($(ls log.* | wc -l) + 1))).$(date +"%Y-%m-%d-%H-%M-%S-%N")'
alias gchrl='gchr 2>&1 | tee log.$(seq -f "%02g" $(($(ls log.* | wc -l) + 1)) $(($(ls log.* | wc -l) + 1))).$(date +"%Y-%m-%d-%H-%M-%S-%N")'
alias gi='ssh gitery init-db $(basename $(pwd))'
alias gc='ssh gitery clone $(git remote get-url origin) $(basename $(pwd))'
alias gd='ssh gitery default-branch $(basename $(pwd)) sisyphus'
alias gra='git remote add geochip gitery:packages/$(basename $(pwd)).git'
