#!/bin/sh

alias ls='exa --group-directories-first'
alias ll='ls -lah'
alias grep='grep --color=auto'

alias ghl='mkdir -p ~/tmp/hasher && gear -v --hasher -- hsh -v 2>&1 | tee log.$(seq -f "%02g" $(($(ls log.* | wc -l) + 1)) $(($(ls log.* | wc -l) + 1))).$(date +"%Y-%m-%d-%H-%M-%S-%N")'
alias gchl='mkdir -p ~/tmp/hasher && gear -v --commit --hasher -- hsh -v 2>&1 | tee log.$(seq -f "%02g" $(($(ls log.* | wc -l) + 1)) $(($(ls log.* | wc -l) + 1))).$(date +"%Y-%m-%d-%H-%M-%S-%N")'
alias ghrl='mkdir -p ~/tmp/hasher && gear -v --hasher -- hsh-rebuild -v 2>&1 | tee log.$(seq -f "%02g" $(($(ls log.* | wc -l) + 1)) $(($(ls log.* | wc -l) + 1))).$(date +"%Y-%m-%d-%H-%M-%S-%N")'
alias gchrl='mkdir -p ~/tmp/hasher && gear -v --commit --hasher -- hsh-rebuild -v 2>&1 | tee log.$(seq -f "%02g" $(($(ls log.* | wc -l) + 1)) $(($(ls log.* | wc -l) + 1))).$(date +"%Y-%m-%d-%H-%M-%S-%N")'
alias gi='ssh gitery init-db $(basename $(pwd))'
alias gd='ssh gitery default-branch $(basename $(pwd)) sisyphus'
