#!/usr/bin/env python3

import argparse
import re
import subprocess


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("name")
    parser.add_argument("command")
    parser.add_argument("binding")
    return parser.parse_args()


def main():
    args = parse_args()

    res = subprocess.run(
        [
            "gsettings",
            "get",
            "org.gnome.settings-daemon.plugins.media-keys",
            "custom-keybindings",
        ],
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    custom_bindings = res.stdout.strip()[1:-1].replace("'", "").split(", ")

    # the last char in custom_binding is '/'
    schema_path = custom_bindings[-1]
    schema_path_base, custom_name = schema_path[:-1].rsplit("/", 1)
    match = re.match(r"custom(?P<number>\d+)", custom_name)
    if not match:
        raise RuntimeError(f"invalid relocatable schema path: {schema_path!r}")

    number = int(match.group("number"))
    new_binding_schema_path = f"{schema_path_base}/custom{number + 1}/"

    if new_binding_schema_path in custom_bindings:
        raise RuntimeError(
            f"tried to override existing schema path: {new_binding_schema_path!r}"
        )

    custom_bindings.append(new_binding_schema_path)
    subprocess.run(
        [
            "gsettings",
            "set",
            "org.gnome.settings-daemon.plugins.media-keys",
            "custom-keybindings",
            str(custom_bindings),
        ],
        check=True,
    )

    subprocess.run(
        [
            "gsettings",
            "set",
            f"org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:{new_binding_schema_path}",
            "name",
            args.name,
        ],
        check=True,
    )
    subprocess.run(
        [
            "gsettings",
            "set",
            f"org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:{new_binding_schema_path}",
            "command",
            args.command,
        ],
        check=True,
    )
    subprocess.run(
        [
            "gsettings",
            "set",
            f"org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:{new_binding_schema_path}",
            "binding",
            args.binding,
        ],
        check=True,
    )


if __name__ == "__main__":
    main()
