# pi coding aget stuff

set -g extended-keys on
set -g extended-keys-format csi-u

# Default shell
set-option -g default-shell /bin/bash

# Neovim stuff
set-option -s default-terminal tmux-256color
set-option -sg escape-time 10
set-option -g focus-events on

# Settign prefix key
unbind-key C-b
set-option -g prefix C-f
bind-key C-f send-prefix

# For copying
set-option -gw mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Start window count from 1
set-option -g base-index 1

# List of plugins
set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-sensible'
set-option -g @plugin 'dracula/tmux'

# Dracula customizations
set-option -g @dracula-plugins "git battery time"
set-option -g @dracula-show-powerline true
set-option -g @dracula-show-fahrenheit false
set-option -g @dracula-day-month true
set-option -g @dracula-military-time true

# BINDINGS
bind-key -r f run-shell "tmux new-window ~/.local/bin/tmux-sessionizer"
# For refreshing the config
bind-key r source-file ~/.tmux.conf
bind-key m run-shell "tmux-sessionizer ~/Dropbox/notable/notes"

# Switching panes with vim-like mappings
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
